name: Pull request into master

on: 
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run unit tests
      run: |
        echo running unit tests
        CI=true npm test